// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvwbmeykhdslijuhzsbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2d2JtZXlraGRzbGlqdWh6c2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NzU3MzMsImV4cCI6MjA3MzM1MTczM30.xbHhkSGAGAXJ6KQ90bqAPKFEbPfeDTK9jaAdKwzoONw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});